"""Update forgotten fields

Revision ID: 004542971f12
Revises: 
Create Date: 2022-04-08 23:16:39.812598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004542971f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['creator_id'], ['id'])
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'creator_id')
    # ### end Alembic commands ###
