"""empty message

Revision ID: 1c841e5a584d
Revises: d62456509a95
Create Date: 2022-05-12 01:00:09.926456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c841e5a584d'
down_revision = 'd62456509a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_types', sa.Column('can_vote', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_types SET can_vote = false")
    op.alter_column('user_types', 'can_vote', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_types', 'can_vote')
    # ### end Alembic commands ###
