"""Added back last_edited column to comments and ratings

Revision ID: 421519d2cbd9
Revises: 1bffd7ac8254
Create Date: 2022-04-10 09:14:49.193730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421519d2cbd9'
down_revision = '1bffd7ac8254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('last_edited', sa.DateTime(), nullable=False))
    op.add_column('ratings', sa.Column('last_edited', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'last_edited')
    op.drop_column('comments', 'last_edited')
    # ### end Alembic commands ###
