"""one-to-one rel between review and post

Revision ID: d62456509a95
Revises: 41724ab22d24
Create Date: 2022-04-14 13:36:21.449263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62456509a95'
down_revision = '41724ab22d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reviews', ['post_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    # ### end Alembic commands ###
